spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
logging:
  file:
    name: logfile.log
